### ISSUE TITLE
Is there a version for armv7l hardware (Raspbery Pi)?

### ISSUE THREAD

**Issue by mysmartbus** [tleyden/open-ocr#101]
Installation failed on a Docker swarm running on Raspberry Pi's.

Everything installed correctly but none of the services would replicate or start.

`Docker service ps` gives the error message: `no suitable node (unsupported platform...)`.

`Docker service inspect` shows that all of the services are expecting amd64 hardware.

Is there a version of open-ocr that will run on a Raspberry Pi (armv7l)?

**Comment by tleyden** [comment]
Nope, you'd be the first to make that work!

**Comment by mysmartbus** [comment]
Ok.

Looking through the code and Dockerfile's, it looks like getting this running on a Raspberry Pi cluster will be as simple as changing the `FROM` line in the Dockerfiles to point to the arm32v7 version of the base package.

Got rabbitmq running by changing the docker-compose file to use `arm32v7/rabbitmq:3.6.15-management`.

I'm going to find out how simple the rest of it really is.

**Comment by mysmartbus** [comment]
Sucess!

Well, it is as long as you do not use the stroke-width-transform preprocessor. open-ocr times out after 2 minutes with the message: "Unable to perform OCR decode.  Error: Timeout waiting for RPC response"

Currently uses libtesseract3 because I could not get libtesseract4 to install from the ppa (ppa:alex-p/tesseract-ocr). Keep getting told libtesseract4 does not exist. Might have to build and install libtesseract4 from source code.

The only changes I needed to make were to the dockerfiles.

The dockerfiles are available from https://github.com/mysmartbus/open-ocr.
