### ISSUE TITLE
Java client for open-OCR

### ISSUE THREAD

**Issue by faLekGG** [tleyden/open-ocr#111]
Hello, @tleyden! I hope in the future it will help someone to figure out some problems how to work with open-ocr. I was stucked a bit with uploading files from Filesystem, so when problem has been resolved I decided upgrade and build lightweight client in Java - https://github.com/faLekGG/JavaOpenOCR

**Comment by tleyden** [comment]
Thanks for your contribution @faLekGG!  I linked it from the [README](https://github.com/tleyden/open-ocr/blob/master/README.md#client-libraries)
