### ISSUE TITLE
RPC Timeout

### ISSUE THREAD

**Issue by jtgreen** [tleyden/open-ocr#22]
This may be an easy one. Im simply trying to run the stoke width transform. The setup works great for straight tesseract, but when I run the test curl for the stoke width transform, I get an RPC timeout. My suspicion is my box is taking too long with the transform so the RPC is kicking back that general network error thinking the call had failed (it not knowing if its a slow network or what). 

Here is the error: 
john@...$ curl -X POST -H "Content-Type: application/json" -d '{"img_url":"http://bit.ly/ocrimage-swt","engine":"tesseract", "preprocessors":["stroke-width-transform"]}' http://${DOCKER_HOST}:${HTTP_PORT}/ocr

<long pause> 

Unable to perform OCR decode.  Error: Timeout waiting for RPC response

Thoughts? 

Thanks!

**Comment by kimmobrunfeldt** [comment]
I'm getting this same error but I have set the password. Worker logs don't have anything

**Comment by kimmobrunfeldt** [comment]
I didn't have the preprocessor worker started as documented here https://github.com/tleyden/open-ocr/wiki/Stroke-Width-Transform#start-an-additional-worker

Same as this issue: https://github.com/tleyden/open-ocr/issues/24

**Comment by tleyden** [comment]
@kimmobrunfeldt can you open a new issue instead of using this one? (since it's closed)

**Comment by kimmobrunfeldt** [comment]
@tleyden sorry I thought my issue related to this. But I got that solved by following instructions in issue thread #24.
