### ISSUE TITLE
what is the CURL command for local image file at /tmp/ocrimage.png

### ISSUE THREAD

**Issue by bx5974** [tleyden/open-ocr#27]
how do you run a CURL command for local image file at /tmp/ocrimage.png

the docs are misleading / confusing for the CURL with local file 

http://docs.openocr.apiary.io/

**Comment by amirbaroz** [comment]
Does anyone have a working example of /ocr-upload-file ?
using curl or any post url example ?

Regards
Amir

**Comment by tleyden** [comment]
@amirbaroz did you see https://github.com/tleyden/open-ocr/blob/master/docs/upload-local-file.sh?

**Comment by amirbaroz** [comment]
first of all - thanks for replaying. I am over this for two days... reading almost every example in the web

I can't understand how to transfer to content of pdf file I want to translate.
I open the file and read it to variable and the print it in the body section  insted of PNGDATA......
the result is emty string after posting the url
I also don't understand why writing the name of attach file filename="attachment.txt"

Regards
Amir

**Comment by tleyden** [comment]
I would make sure your PDF -> PNG is working by manually inspecting the PNG file and make sure it looks right.

Once you have a PNG, feeding it to openocr should be trivial with https://github.com/tleyden/open-ocr/blob/master/docs/upload-local-file.sh

**Comment by amirbaroz** [comment]
I dowload the example ocr_test.png, so  I am sure the file is not the problem
I install the entire project and get result for regular /ocr (using url for file need to be translate)
I need a saas solution, so I can post a url request and get back string oof ocr resulat.
I don't want to run script in the server, I whant to write a request post pbject that upload the file in the post method.
Did you try to do something like that and it worked for you ? 

Regards
Amir

**Comment by tleyden** [comment]
Yes everything is working to my knowledge.  

For an example of sending a POST request from code, see: https://github.com/tleyden/open-ocr-client/blob/master/ocr_http_client.go#L26-L113

**Comment by amirbaroz** [comment]
thanks
