### ISSUE TITLE
connect to rabbitmq error on Ubuntu 14.04

### ISSUE THREAD

**Issue by zhao0** [tleyden/open-ocr#37]
Hi,
I install it following README step by step,but when I test the API,I got a error :Unable to perform OCR decode.  Error: dial tcp 127.0.0.1:5672: connection refused.

here is my docker ps
CONTAINER ID        IMAGE                         COMMAND                CREATED             STATUS              PORTS                                              NAMES
113840c08653        tleyden5iwx/open-ocr:latest   open-ocr-worker -amq   11 seconds ago      Up 10 seconds                                                          stoic_pike  
5b7c8a8d9340        tleyden5iwx/open-ocr:latest   open-ocr-httpd -amqp   14 seconds ago      Up 12 seconds       0.0.0.0:8080->8080/tcp                             evil_lalande  
090b2f66c809        tutum/rabbitmq:latest         /run.sh                46 seconds ago      Up 45 seconds       0.0.0.0:5672->5672/tcp, 0.0.0.0:15672->15672/tcp   nostalgic_brown

**Comment by zhao0** [comment]
rabbitmq log blow:
BOOT FAILED
===========

Error description:
   {boot_step,networking,
       {case_clause,
           {error,
               {{shutdown,
                    {failed_to_start_child,tcp_listener,
                        {cannot_listen,{0,0,0,0,0,0,0,0},5672,eaddrinuse}}},
                {child,undefined,'rabbit_tcp_listener_sup_:::5672',
                    {tcp_listener_sup,start_link,
                        [{0,0,0,0,0,0,0,0},
                         5672,
                         [inet6,binary,
                          {packet,raw},
                          {reuseaddr,true},
                          {backlog,128},
                          {nodelay,true},
                          {linger,{true,0}},
                          {exit_on_close,false}],
                         {rabbit_networking,tcp_listener_started,[amqp]},
                         {rabbit_networking,tcp_listener_stopped,[amqp]},
                         {rabbit_networking,start_client,[]},
                         "TCP Listener"]},
                    transient,infinity,supervisor,
                    [tcp_listener_sup]}}}}}

**Comment by tleyden** [comment]
5672,eaddrinuse means you have something (RabbitMQ?) already listening on that port.

**Comment by zhao0** [comment]
I just install it on a new machine

**Comment by wicope** [comment]
Hi,
https://docs.docker.com/compose/startup-order/

**Comment by tleyden** [comment]
Thanks @wicope!  That's a much cleaner approach than the current docker compose file

**Comment by wicope** [comment]
```
docker ps -a
c30dd164a980        tleyden5iwx/open-ocr                "/opt/open-ocr/open-o"   18 minutes ago      Exited (2) 17 minutes ago                            dockercompose_openocrworker_1
```

```
docker logs c30dd164a980
14:12:13.176167 OCR_WORKER: Creating new OCR Worker
14:12:13.185760 OCR_WORKER: Run() called...
14:12:13.186077 OCR_WORKER: dialing "amqp://admin:Cdoe4O8oOalghout4FR4cqfx@rabbitmq/"
14:12:13.322935 OCR_WORKER: error connecting to rabbitmq dial tcp 172.18.0.2:5672: connection refused
14:12:13.323108 PANIC: Error running worker: dial tcp 172.18.0.2:5672: connection refused -- main.main() at main.go:36
panic: Error running worker: dial tcp 172.18.0.2:5672: connection refused
...
```

https://github.com/docker/compose/blob/master/docs/compose-file.md#depends_on

Controlling startup order in Compose
https://docs.docker.com/compose/startup-order/
https://github.com/docker/compose/blob/master/docs/startup-order.md
https://github.com/vishnubob/wait-for-it
https://github.com/jwilder/dockerize
http://www.onegeek.com.au/articles/waiting-for-dependencies-in-docker-compose
https://github.com/docker/compose/issues/374

**Comment by tleyden** [comment]
Would be great if someone could do pull request to fix the docker compose file

**Comment by tleyden** [comment]
Looks like this was already merged: https://github.com/tleyden/open-ocr/blob/master/docker-compose/docker-compose.yml#L31
