### ISSUE TITLE
hOCR output?

### ISSUE THREAD

**Issue by jbarlow83** [tleyden/open-ocr#38]
Is there a way to use the REST API to request hOCR output from Tesseract via open-ocr?

Using standalone tesseract a command to do with could be:
`tesseract -l eng inputfile.png output hocr tess.cfg`

**Comment by jbarlow83** [comment]
Found the answer:
```shell
curl -X POST -H "Content-Type: application/json" -d \
'{"img_url":"http://bit.ly/ocrimage","engine":"tesseract","engine_args":{"config_vars":{"tessedit_create_hocr":"1"}}}' \
http://$IPADDR:$PORT/ocr```

**Comment by tleyden** [comment]
Thanks for posting the solution!
