### ISSUE TITLE
Unable to connect from public dns (AWS)

### ISSUE THREAD

**Issue by wedkarz** [tleyden/open-ocr#41]
While testing connection it passes on public ip 
```curl -X POST -H "Content-Type: application/json" -d '{"img_url":"http://bit.ly/ocrimage","engine":"tesseract"}' http://172.31.43.136:8080/ocr```
if run from httpd.service instance.

But when I try do it from the same machine but via public DNS: 
```curl -X POST -H "Content-Type: application/json" -d '{"img_url":"http://bit.ly/ocrimage","engine":"tesseract"}' http://ec2-52-18-254-60.eu-west-1.compute.amazonaws.com:8080/ocr```

from local machine, I've got curl: 
    (7) Failed to connect to ec2-52-17-28-26.eu-west-1.compute.amazonaws.com port 8080: Connection refused

Any ideas?

**Comment by tleyden** [comment]
I don't know, but it seems more like an AWS config issue rather than a bug in the code.  Re-open if you can show otherwise.

**Comment by wedkarz** [comment]
I agree, but could you help with aws a little? what might be the cause? I have security group configured to allow TCP connections on port 8080.
