### ISSUE TITLE
ERROR: Get http://bit.ly/ocrimage: dial tcp: lookup bit.ly: no such host

### ISSUE THREAD

**Issue by arinbec** [tleyden/open-ocr#45]
After setting up the docker containers, the following error is given while testing

ERROR: Get http://bit.ly/ocrimage: dial tcp: lookup bit.ly: no such host

Seems to be that docker container has no access to outside network.

**Comment by tleyden** [comment]
I think that must be an issue of your hosting company or misconfiguration of your host.  Closing the issue since I don't see any action items, but feel free to post any follow up info.
