### ISSUE TITLE
Unable to test SWT preprocessor

### ISSUE THREAD

**Issue by Omnipresent** [tleyden/open-ocr#46]
I followed the documentation for AWS to set everything up https://github.com/tleyden/open-ocr/wiki/Installation-on-CoreOS-Fleet

Although the OCR works, it doesn't work with the preprocessor. 

```bash
curl -X POST -H "Content-Type: application/json" -d '{"img_url":"http://bit.ly/ocrimage-swt","engine":"tesseract", "preprocessors":["stroke-width-transform"]}' http://_my_httpd_service:8080/ocr
Unable to perform OCR decode.  Error: Timeout waiting for RPC response
```

**Comment by Omnipresent** [comment]
I've added the steps needed to verify Stroke Width Transform to the AWS documentation 4ed77a4

**Comment by tleyden** [comment]
> I've added the steps needed to verify Stroke Width Transform to the AWS documentation

Thanks!  I didn't realize anyone could edit the wiki!

**Comment by Omnipresent** [comment]
/offtopic/
heh me too. I wanted to reference a change prior to closing the issue but don't think wikis are even tracked with git. Which is unfortunate.

**Comment by tleyden** [comment]
Actually they are: 

```
git clone https://github.com/tleyden/open-ocr.wiki.git
```
