### ISSUE TITLE
always return the same

### ISSUE THREAD

**Issue by joseramz** [tleyden/open-ocr#50]
I have my server running, when i enter to 192.168.0.164 i can see 

OpenOCR is running!
Need docs?

same with localhost.
But when i send requests like this:
curl -X POST -H "Content-Type: application/json" -d '{"img_url":"http://bit.ly/ocrimage","engine":"tesseract"}' http://192.168.0.164:8080

the response is: 

OpenOCR is running!
Need docs?
am i doing anything wrong?

Thanks

**Comment by tleyden** [comment]
You're missing the endpoint!

Try:

```
curl -X POST -H "Content-Type: application/json" -d '{"img_url":"http://bit.ly/ocrimage","engine":"tesseract"}' http://192.168.0.164:8080/ocr
```

Does that work?
