### ISSUE TITLE
How do I know what version of tesseract this is using?

### ISSUE THREAD

**Issue by simkimsia** [tleyden/open-ocr#55]
The reason is because I want to add training for more languages and it differs depending if tesseract 2 or tesseract 3.

The latest is v3.04.01 on Feb 2016

**Comment by tleyden** [comment]
Here are the dockerfiles:

https://github.com/tleyden/docker/blob/master/open-ocr/Dockerfile
https://github.com/tleyden/docker/blob/master/open-ocr-preprocessor/Dockerfile

(I need to move them into this repo)

Looks like its tesseract 3 from the libtesseract3 dependency.

Which languages?

**Comment by simkimsia** [comment]
Thank you

**Comment by tleyden** [comment]
@simkimsia let me know if you need me to trigger a rebuild of the docker image to get the latest tesseract packages (or add more language packs)

**Comment by simkimsia** [comment]
Would like to add Chinese PRC language.

Thank you!

**Comment by tleyden** [comment]
Can you get me the exact name of the package?

Already have these included:

```
tesseract-ocr-chi-sim 
tesseract-ocr-chi-tra
```

https://github.com/tleyden/docker/blob/master/open-ocr/Dockerfile#L45-L46

**Comment by simkimsia** [comment]
Weird.

How do I then make the ocr detect chinese and English on same document at
same time?

**Comment by tleyden** [comment]
That I don't know how to do or whether it's possible.  Would you mind asking on the [Tesseract Google Group](https://groups.google.com/forum/#!forum/tesseract-ocr)?  If you find anything interesting, please update this ticket!
