### ISSUE TITLE
How can I run open-ocr on IBM bluemix

### ISSUE THREAD

**Issue by jiangkid** [tleyden/open-ocr#60]
Hi,
Can you give an instruction for lanching open-ocr on IBM bluemix?

**Comment by tleyden** [comment]
I'm happy to help, but you're probably going to need to drive this forward on your own, or open a Bluemix support ticket.

It looks like they support Docker compose, and OpenOCR ships with a Docker compose file, so I'd start from there.

I'm closing this ticket but feel free to post more questions or info!  If you provide instructions I will be happy to add them to a wiki page.

**Comment by tleyden** [comment]
See https://github.com/tleyden/open-ocr/issues/61
