### ISSUE TITLE
Container command '/opt/open-ocr/open-ocr-httpd' not found or does not exist. Ubuntu 15.10

### ISSUE THREAD

**Issue by FBurner** [tleyden/open-ocr#63]
Hi,

Im getting **"Container command '/opt/open-ocr/open-ocr-httpd' not found or does not exist."** on

**sudo docker-compose up**

on ubuntu 15.10

**Comment by tleyden** [comment]
Can you post the full logs of your docker compose output?

**Comment by tleyden** [comment]
Seems to be a duplicate of https://github.com/tleyden/open-ocr/issues/66, but I have no idea how to reproduce this.
