### ISSUE TITLE
"/opt/open-ocr/open-ocr-httpd": stat /opt/open-ocr/open-ocr-httpd: no such file or directory

### ISSUE THREAD

**Issue by GeorgeAnanthSoosai** [tleyden/open-ocr#66]
getting following error when i did docker up on my windows 7 machine, 

$ docker-compose up -d
dockercompose_rabbitmq_1 is up-to-date
Starting dockercompose_strokewidthtransform_1
Starting dockercompose_openocr_1
Starting dockercompose_openocrworker_1

ERROR: for strokewidthtransform  Cannot start service strokewidthtransform: oci runtime error: exec: "/opt/open-ocr/open-ocr-preprocessor": stat /opt/open-ocr/open-ocr-preprocessor: no such file or directory

ERROR: for openocr  Cannot start service openocr: oci runtime error: exec: "/opt/open-ocr/open-ocr-httpd": stat /opt/open-ocr/open-ocr-httpd: no such file or directory

ERROR: for openocrworker  Cannot start service openocrworker: oci runtime error: exec: "/opt/open-ocr/open-ocr-worker": stat /opt/open-ocr/open-ocr-worker: no such file or directory
←[31mERROR←[0m: Encountered errors while bringing up the project.

Please verify and advise me if anything I've missed!!!

**Comment by tleyden** [comment]
Thanks for the bug report!

**Comment by tleyden** [comment]
I just tried it and it worked.  Here are my logs: https://gist.github.com/tleyden/e56b124fc9a1e150bd05c4b9d724b209

Not sure how to reproduce this, so going to proactively close the ticket.  If you can give clear steps to reproduce it I'll re-open it.  

I have a feeling it might be something related to the specific environment you are running in.

**Comment by GeorgeAnanthSoosai** [comment]
Thank for your quick reply sir.. 

I did the following steps to use ocr on my machine.. 

Install docker
Install docker toolbox  -- installed
Checkout OpenOCR repository
cd docker-compose directory
docker-machine start default
docker-machine env
Look at the Docker host IP address

-- upto above steps i didn't get any error.. 

But when I exuecute the below one.. I run into the error, 

Run docker-compose up -d to run containers as daemons or docker-compose up to see the log in console

I'm trying all this on  my windows machine.. Do I missed anything here ?

**Comment by tleyden** [comment]
If you run `docker images` do you get the same as these?


```
tleyden5iwx/open-ocr                        latest              f06cde5be4da        4 months ago        1.522 GB
tleyden5iwx/open-ocr-preprocessor           latest              00a689ddd4f8        2 years ago         1.313 GB
```

**Comment by alex-doe** [comment]
I'm having the same issue. Also a windows environment. Maybe a volume mounting issue in docker-compose like https://github.com/docker/compose/issues/2548
``` 
Windows 10 Pro x64
Docker for Windows 1.12.1, build 23cf638
```

**Comment by GeorgeAnanthSoosai** [comment]
$ docker images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
ubuntu                              14.04               b1719e1db756        2 days ago          188 MB
tleyden5iwx/open-ocr                latest              a0463bac40c1        10 days ago         1.523 GB
rabbitmq                            latest              0463354ada4d        4 weeks ago         180.8 MB
hello-world                         latest              c54a2cc56cbb        11 weeks ago        1.848 kB
tutum/rabbitmq                      latest              b16f4591e580        6 months ago        227.7 MB
tleyden5iwx/open-ocr-preprocessor   latest              00a689ddd4f8        2 years ago         1.313 GB

**Comment by tleyden** [comment]
@alex-doe sounds possible, but in https://github.com/tleyden/open-ocr/issues/63 there was a similar error, which was on Ubuntu.

**Comment by GeorgeAnanthSoosai** [comment]
@tleyden @alex-doe  -- Could you please share me the updated configuration changes for Windows ?

**Comment by alex-doe** [comment]
@GeorgeAnanthSoosai I'm currently having no solution for this problem.

**Comment by GeorgeAnanthSoosai** [comment]
Thanks @alex-doe.. 

@tleyden -- Will you please help me on this ?

**Comment by alex-doe** [comment]
@GeorgeAnanthSoosai have a look at pr #65.
Removing the `/opt/open-ocr/` in `docker-compose.yml` solved the problem at my machine.

**Comment by tleyden** [comment]
@alex-doe that approach will cause other problems though -- because now there will be nothing to guarantee the startup order.  The deeper fix for the compose file is to use:

```
    depends_on:
      - "rabbitmq"
```

as described in https://docs.docker.com/compose/startup-order/

**Comment by GeorgeAnanthSoosai** [comment]
Thank you very much @tleyden -- It's working now.. Great help.. much appreciated!!

**Comment by GeorgeAnanthSoosai** [comment]
@tleyden -- It seems rabbitmq is not setting up properly.. Can you please share me the updated config file ?

**Comment by tleyden** [comment]
See https://github.com/tleyden/open-ocr/issues/74
