### ISSUE TITLE
convert bash command to PHP

### ISSUE THREAD

**Issue by Gutz-Pilz** [tleyden/open-ocr#67]
`bash -x upload-local-file.sh http://192.168.0.107:9292/ocr-file-upload webcam.jpg`

gives me this

`curl -v -X POST http://192.168.0.107:9292/ocr-file-upload --header 'Content-Type: multipart/related; boundary="2ac80ee2f500dbe0bae6d3148fe4f960"' --data-binary @-`

How can I convert this command to PHP?

I'm really a noob in WEB-Dev and would really appreciate a sample php code that will imitate that command.

**Comment by tleyden** [comment]
I think if you're a noob, you should check out [Paw](https://paw.cloud/) -- you can build a REST API in their GUI, and then export to PHP.

If it's useful, here is some [golang code](https://github.com/tleyden/open-ocr-client/blob/master/ocr_http_client.go#L26-L113) that does the upload.  You might be able to find someone who knows php that could convert it fairly easily.

Actually, this might be the easiest:

Go to http://docs.openocr.apiary.io/#reference/openocr/ocr-decode-via-file-upload/ocr-decode and choose PHP.  It's outputting:

```
<?php
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "http://openocr.yourserver.com/ocr-file-upload");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
curl_setopt($ch, CURLOPT_HEADER, FALSE);

curl_setopt($ch, CURLOPT_POST, TRUE);

curl_setopt($ch, CURLOPT_POSTFIELDS, -----BOUNDARY
Content-Type: application/json

{\"engine\":\"tesseract\"}
-----BOUNDARY

-----BOUNDARY
Content-Disposition: attachment;
Content-Type: image/png
filename=\"attachment.txt\".

PNGDATA.........
-----BOUNDARY);

curl_setopt($ch, CURLOPT_HTTPHEADER, array(
  "Content-Type: multipart/related; boundary=---BOUNDARY"
));

$response = curl_exec($ch);
curl_close($ch);

var_dump($response);
```

You will need to replace the URLs with the ones on your server.

**Comment by GeorgeAnanthSoosai** [comment]
@tleyden -- what should we pass in the PNGDATA......... ? 

also, can i pass the content type as Content-Type: image/*  ?
