### ISSUE TITLE
Working samples for javascript code as same as "https://github.com/tleyden/open-ocr-client" 

### ISSUE THREAD

**Issue by GeorgeAnanthSoosai** [tleyden/open-ocr#70]
I tried https://github.com/tleyden/open-ocr-client this.. it is working great!.. i need to do the samething in Javascript.. Can you please give me the working samples in javascript ?

I'm not able to construct the payload which server expect.. Please give me the working samples on javascript as well..

**Comment by tleyden** [comment]
The best I can tell you is to to http://docs.openocr.apiary.io/#reference/openocr/ocr-decode-via-file-upload/ocr-decode and choose "javascript"

```
var request = new XMLHttpRequest();

request.open('POST', 'http://openocr.yourserver.com/ocr-file-upload');

request.setRequestHeader('Content-Type', 'multipart/related; boundary=---BOUNDARY');

request.onreadystatechange = function () {
  if (this.readyState === 4) {
    console.log('Status:', this.status);
    console.log('Headers:', this.getAllResponseHeaders());
    console.log('Body:', this.responseText);
  }
};

var body = "-----BOUNDARY \
Content-Type: application/json \
 \
{'engine':'tesseract'} \
-----BOUNDARY \
 \
-----BOUNDARY \
Content-Disposition: attachment; \
Content-Type: image/png \
filename='attachment.txt'. \
 \
PNGDATA......... \
-----BOUNDARY";

request.send(body);
```

Otherwise, you're on your own!  All the answers should be in the client reference implementation though: https://github.com/tleyden/open-ocr-client .

**Comment by GeorgeAnanthSoosai** [comment]
I tried exactly same you gave on this  http://docs.openocr.apiary.io/#reference/openocr/ocr-decode-via-file-upload/ocr-decode portal.. 

Noting works for me.. all the time I'm getting "runtime error: invalid memory address or nil pointer dereference" from the server

**Comment by GeorgeAnanthSoosai** [comment]
I've the base64 image data -- which I mappped on PNGDATA.. 

var body = "-----BOUNDARY \
Content-Type: application/json \
 \
{'engine':'tesseract'} \
-----BOUNDARY \
 \
-----BOUNDARY \
Content-Disposition: attachment; \
Content-Type: image/png \
filename='attachment.txt'. \
 \
base64 png image data  \
-----BOUNDARY";

As we see, body is a string which has the boundary and within the boundary i've defined the base64 image data -- Not sure why it wasn't working from Javascript rest call.. 

I've tried all the way.. nothing working for me..
