### ISSUE TITLE
getting "runtime error: invalid memory address or nil pointer dereference" for file upload from Javascript

### ISSUE THREAD

**Issue by GeorgeAnanthSoosai** [tleyden/open-ocr#71]
**Error message :**
167 +0x7b7
←[35mopenocr_1               |←[0m created by net/http.(*Server).Serve
←[35mopenocr_1               |←[0m      /usr/lib/go/src/pkg/net/http/server.go:1
644 +0x28b
←[35mopenocr_1               |←[0m 04:24:22.441660 ←[33mOCR_HTTP: ←[0mrequest to
 ocr-file-upload
←[35mopenocr_1               |←[0m 04:24:22.441799 ←[33mOCR_HTTP: ←[0mcontent ty
pe: multipart/related; boundary=---BOUNDARY
←[35mopenocr_1               |←[0m 04:24:22.442037 ←[33mOCR_HTTP: ←[0mcontent ty
pe: multipart/related
←[35mopenocr_1               |←[0m 2016/09/28 04:24:22 http: panic serving 192.1
** 68.99.1:64828: runtime error: invalid memory address or nil pointer dereference**
←[35mopenocr_1               |←[0m goroutine 13 [running]:
←[35mopenocr_1               |←[0m net/http.func┬╖009()
←[35mopenocr_1               |←[0m      /usr/lib/go/src/pkg/net/http/server.go:1
093 +0xae
←[35mopenocr_1               |←[0m runtime.panic(0x6afb80, 0xa21f28)
←[35mopenocr_1               |←[0m      /usr/lib/go/src/pkg/runtime/panic.c:248
+0x106

Given Payload:
Header : Content-Type:multipart/related; boundary=---BOUNDARY

Body : 
-----BOUNDARY Content-Type: application/json  {'engine':'tesseract'} -----BOUNDARY  -----BOUNDARY Content-Type: image/PNG Content-Disposition: attachment; filename='attachment.txt'. PNG


IHDR$T9',tEXtSoftwareAdobe ImageReadyqÉe<»IDATxÚì}¸U¹öZ3»iÞ!tP¤í·*kçZPÄrTô^AÀ ÷WQÅvQTàZ(bA¥(¨$º÷Yÿ|k­of­i{v;-ßg2ûì2{fö*ïz¿Æ@ a:Á»}¬5­X8XuVâ×m÷ºt	@½X1öð7Ü¶7<ñèVg=þ¨~©+ª#ùùþs»­ÌwøåìÊ¿k¥:oÞèÖûîVsvßsþàFú)	@½xªáô­ÙÈ:Þ=¥Ç~ù¯Íîü5ûÿéîE¼oéûÿùÉ-¦DdëAgåMË_yôüE;Æ·Úå9óïÕÏªóØÖÕ>¶ýàë/è$ac¼Ñ`{ÉìñÇï^=¸þÞóýíÆ½×Ýö»<jI;ßÏ×_²ýÊß/>á¸òv2°ÝaÇ
,Úí±`>@ ¶ ²fÍý«n¸nñ?ñýýÞzËõ!)LJZ%$	É¿.Ùþ¸»wxùÞ^¯zÕÐ6;U\¼~@ ¶P<°i{ú¿{Üýãç¾PyôÎÿ^ù'7°Ô¢äÎËýÂ§v~á»Ý½_uì3-#E@ [?1Éîzò±Ú¼;.ºj»G~zázâN	IF5­8ö/Ç|á .... 

-----BOUNDARY

Please review above and advise me what went wrong..

**Comment by GeorgeAnanthSoosai** [comment]
@tleyden  - any update on this ?

**Comment by tleyden** [comment]
@GeorgeAnanthSoosai  This doesn't look like an issue in open-ocr, so I'm closing this ticket.  If you can provide clear instructions to reproduce an issue with [open-ocr-client](https://github.com/tleyden/open-ocr-client)

Otherwise, it's your client code that's probably broken.
