### ISSUE TITLE
docker-compose up is error "Error running worker: dial tcp 172.17.0.2:5672: connection refused"

### ISSUE THREAD

**Issue by GeorgeAnanthSoosai** [tleyden/open-ocr#73]
←[32mopenocrworker_1         |←[0m 03:18:14.297072 ←[33mOCR_WORKER: ←[0merror connecting to rabbitmq dial tcp 172.17.0.2:5672: connection refused
←[32mopenocrworker_1         |←[0m 03:18:14.297334 ←[31mPANIC: Error running worker: dial tcp 172.17.0.2:5672: connection refused←[0m←[2m -- main.main() at main.go:36←[0m
←[32mopenocrworker_1         |←[0m panic: Error running worker: dial tcp 172.17.0.2:5672: connection refused

**Comment by tleyden** [comment]
See https://github.com/tleyden/open-ocr/issues/74
