### ISSUE TITLE
 fopenReadStream: file not found 

### ISSUE THREAD

**Issue by GeorgeAnanthSoosai** [tleyden/open-ocr#76]
Getting following exception when trying to read png file, 

Error exec tesseract: exit status 1 Tesseract Open Source OCR Engine v3.03 with Leptonica
 Error in pixReadStream: Unknown format: no pix returned
 Error in pixRead: pix not read
 Error in pixGetInputFormat: pix not defined
 Reading /tmp/8df990cd-9890-4e4d-67d9-ac03bc4f44c2 as a list of filenames...
 Error in fopenReadStream: file not found
 Error in pixRead: image file not found
 Image file ┬ëPNG cannot be read!
 Error during processing.

Error processing image url: .  Error: exit status 1

Error generating ocr result.  Error: exit status 1←

Can you please  advise me what went wrong for this case ?

**Comment by tleyden** [comment]
This is impossible to debug without clear steps to reproduce.

**Comment by GeorgeAnanthSoosai** [comment]
Here is the payload I used.. 

-- -----BOUNDARY
Content-Type: application/json

{"engine":"tesseract"}
-----BOUNDARY
Content-Disposition: attachment; filename="attachment.txt".
Content-Type: image/png

PNG

±`>@ ¶ ²fÍý«n¸nñ?ñýýÞzËõ!)LJZ%$	É¿.Ùþ¸»wxùÞ^¯zÕÐ6;U\¼~@ ¶P<°i{ú¿{Üýãç¾PyôÎÿ^ù'7°Ô¢äÎËýÂ§v~á»Ý½_uì3-#E@ [?1Éîzò±Ú¼;.ºj»G~zázâN	IF5­8ö/Ç|á?ø²}ît÷	@ X¸ç©u¬qçßÞxãÞuü¥k6È#$NQ2òèùÛxß>o?/?È@ T°íbVÛï
§.;ø¨?°Èå#WqW¿~lùNëw<ö£c{~ès·[Fw@ B&V.^Ê<ì§ýíó¾£()qr×¯;¥­þÐþï>@ Í

-----BOUNDARY--
