### ISSUE TITLE
Not able to upload PNG image

### ISSUE THREAD

**Issue by sathishsanthosam** [tleyden/open-ocr#79]
Hi,

I'm trying to upload png image with ocr-file-upload API.
I'm using java script to send the request.
I'm converting the base64 data URI to raw data for png image using atob(base64string).

I'm getting 200 but in the response i getting an error as Error Processing Image URL.

I've attached  the Image for the request and Response.

could you please let me know, what am i missing?

Thanks and Regards,
Sathish.
![request](https://cloud.githubusercontent.com/assets/5171739/19081696/39f6fd0e-8a29-11e6-815d-06a5cb182b89.png)
![response](https://cloud.githubusercontent.com/assets/5171739/19081702/40e15312-8a29-11e6-8319-bfaf70306084.png)

**Comment by tleyden** [comment]
If you want help you will need to post *code* that reproduces your issue, and that is packaged and easy to run.  

Also, if you use an http sniffer tool like [httpscoop](https://www.tuffcode.com/)  or [wireshark](https://www.wireshark.org/) you can compare it with the known working client (https://github.com/tleyden/open-ocr-client) and see what's different on the network.
