### ISSUE TITLE
PNG Image Upload Issue

### ISSUE THREAD

**Issue by sathishsanthosam** [tleyden/open-ocr#80]
Hi,

I'm trying to upload a PNG image with ocr-file upload API.
I'm getting 200, but the response says Error Processing Image URl.
I'v attached JSfiddle to repdoduce.

Could you please let me know, what am i missing?
http://jsfiddle.net/Lvc0u55v/10464/

#79

Thanks and Regards,
Sathish.

**Comment by tleyden** [comment]
No need to base64 it.  

In the golang client, it:

* [Opens the file reader](https://github.com/tleyden/open-ocr-client/blob/b0e82eef193817cdaa910caf2662e4dccff4f365/cli-main/main.go#L51-L59)
* [Copies the raw data into the part](https://github.com/tleyden/open-ocr-client/blob/master/ocr_http_client.go#L65)

**Comment by tleyden** [comment]
Check 

* http://stackoverflow.com/questions/21358176/building-multipart-file-payload-content-correctly
* http://stackoverflow.com/questions/37710660/how-to-send-http-response-with-multipart-related-data-in-nodejs

**Comment by tleyden** [comment]
Closing issue because this does not appear to be a bug in open-ocr

**Comment by sathishsanthosam** [comment]
i'm not sedning the base 64, i'm sending the RAW darta.
atob($scope.getBase64Image()), would convert into Raw data.

**Comment by tleyden** [comment]
`getBase64Image()` is a terrible name for something that doesn't convert it to base64.

**Comment by sathishsanthosam** [comment]
sorry for the confusion i made. i was in a hurry to send the jsfiddle.
I'm sending the actual data, still i'm getting the same error.
please help us.
