### ISSUE TITLE
inaccurate results

### ISSUE THREAD

**Issue by chungtinhlakho** [tleyden/open-ocr#84]
HI all, I final was able to get this up and running.  What i'm trying to do is read the score of a basketball game.  

for the attached picture, this is what it pickup.  some picture, it didn't even pickup anything?

‘\  semis 
1ST 50.9

is there anyway we can train it to be able to recognize this?  or is there anyway i can get a more accurate result?
![period_down_1307](https://cloud.githubusercontent.com/assets/1680647/23495346/10805d30-fecd-11e6-8c79-355a1a9dfb29.png)

**Comment by tleyden** [comment]
I think this is more of a tesseract issue than an openocr issue.

Having said that, openocr does need to upgrade to latest version of tesseract
