### ISSUE TITLE
Installing openOCR on ubuntu 14 

### ISSUE THREAD

**Issue by virgil-av** [tleyden/open-ocr#91]
I am having some trouble installing this, I have followed this steps 
Install docker
Install docker-compose

But I have no idea what should I do from here this detail makes no sense:
Checkout OpenOCR repository or at least copy all files and subdirectories from OpenOCR docker-compose directory

Can someone explain to me how to move forward. Thank you

**Comment by tleyden** [comment]
Check the updated instructions:

https://github.com/tleyden/open-ocr/blob/master/README.md#launching-openocr-command-runsh

Should be less confusing .. if you still get stuck feel free to open up a new issue
