### ISSUE TITLE
How to scale ? 

### ISSUE THREAD

**Issue by speedfl** [tleyden/open-ocr#92]
Hello.
Quick question. 
I know that with docker compose we can use 

    --scale <img>=<number>

Did you already try ?

**Comment by speedfl** [comment]
I see that you propose kubernetes integration I will have a look  :)

**Comment by speedfl** [comment]
I saw that there is open-ocr-worker in replication controller.
Does it mean that I can launch several instances of the worker ?
In such case is rabbitmq which do the load balancing between the workers ?

**Comment by tleyden** [comment]
Yeah you can any number of ocr workers, which will pull off rabbitmq and spread workload across workers

**Comment by tleyden** [comment]
I haven't tried multiple workers via compose, but if you try it and it works, maybe this should be a compose env variable

**Comment by tleyden** [comment]
Gonna close since no action items, but feel free to continue conversation here and/or open more specific issue(s)
