### ISSUE TITLE
Error: signal: illegal instruction

### ISSUE THREAD

**Issue by geeshans** [tleyden/open-ocr#93]
Hi,

I'm running this on a ubuntu (4.4.27-x86_64-jb1) host and had the application successfully working after setup. But now it's throwing the error "Error processing image url: .  Error: signal: illegal instruction (core dumped)" for the sample query. 

```
root@localhost:~/ocr_docker# curl -X POST -H "Content-Type: application/json" -d '{"img_url":"http://bit.ly/ocrimage","engine":"tesseract"}' http://<masked>:8080/ocr
Error processing image url: .  Error: signal: illegal instruction (core dumped)root@localhost:~/ocr_docker#
```

**Comment by geeshans** [comment]
May 16 20:29:39 localhost kernel: traps: tesseract[24223] trap invalid opcode ip:7efccce45448 sp:7efcca7fdd48 error:0
May 16 20:29:39 localhost kernel: traps: tesseract[24221] trap invalid opcode ip:7efccce45448 sp:7ffe4b385628 error:0 in libtesseract.so.4.0.0[7efcccc51000+329000]
May 16 20:29:39 localhost kernel: in libtesseract.so.4.0.0[7efcccc51000+329000]
May 16 20:29:39 localhost kernel:

**Comment by tleyden** [comment]
Thanks for reporting.  Looks like you are using the latest version of tesseract, which was just recently added to open-ocr.

Are you running under docker-compose?  Can you post  the command you're running to start it, including environment variables?

**Comment by geeshans** [comment]
Thanks for getting back to me. 

I'm using "open-ocr/docker-compose/run.sh" to start the process. And yes I was using the tesseract 4.x . I switched to the older version and it worked. 

What are the "environment variables" you require?

**Comment by tleyden** [comment]
I thought there might be an environment variable for specifying the tesseract version.  I haven't tried with 4.0, but thanks for filing a bug.

If it's totally broken, maybe I should rollback https://github.com/tleyden/open-ocr/commit/6566eda7f1cb5e5e7e91228396053dce47d7a2b3

@speedfl any thoughts on this issue?

**Comment by speedfl** [comment]
Hey. I will have a look. Everything was working on my side when I put it in place (I am working with it for some weeks now)
I will be able to test this weekend
I will keep you posted.

**Comment by speedfl** [comment]
Question if you use the ´´´run.sh´´´ with 3.0 it is working ?

**Comment by speedfl** [comment]
Hello Hello

I am back. I was able to test because my girlfriend is not at home tonight :)
So you are right there is a little issue with the docker image of tesseract4 certainly due to a  build issue.

However I fixed it by using a docker image based on unofficial packages of tesseract4 proposed in the docker repo and it is working :)

I will do a PR into docker repository :)

**Comment by speedfl** [comment]
Hey. Can you retry  ?

**Comment by speedfl** [comment]
Hello,

Just for information. I created new instances of open-ocr with open-ocr-2 (I am trying to run multiple instance of open-ocr with a proxy) and the installation and running was perfectly working :)

Creation of 3 different instances each time worked. So I guess we can close the issue

**Comment by tleyden** [comment]
Thanks @speedfl!
