### ISSUE TITLE
Install on OSX error

### ISSUE THREAD

**Issue by awkejiang** [tleyden/open-ocr#94]
$ docker-compose up
WARNING: The OPEN_OCR_INSTANCE variable is not set. Defaulting to a blank string.
Pulling openocrworker (tleyden5iwx/:latest)...
ERROR: Error parsing reference: "tleyden5iwx/" is not a valid repository/tag

**Comment by awkejiang** [comment]
My fault. Need setting up the env first.
$ export OPEN_OCR_INSTANCE=open-ocr-2

**Comment by tleyden** [comment]
Thanks for reporting how you fixed it!
