### ISSUE TITLE
WARNING: The OPEN_OCR_INSTANCE variable is not set. Defaulting to a blank string.

### ISSUE THREAD

**Issue by isathish** [tleyden/open-ocr#96]
$ docker-compose build
WARNING: The OPEN_OCR_INSTANCE variable is not set. Defaulting to a blank string.
rabbitmq uses an image, skipping
strokewidthtransform uses an image, skipping
openocrworker uses an image, skipping
openocr uses an image, skipping

**Comment by tleyden** [comment]
@isathish I agree that's a bit confusing.  But can you explain the observed problem you are seeing?  Eg, actual vs expected?

Also the [instructions](https://github.com/tleyden/open-ocr#launching-openocr-command-runsh) mention to use `docker-compose up`.  Why are you running `docker-compose build`?

**Comment by isathish** [comment]
Please help me the docker-compose.yml file and file path i want make it my local machine.
Please guide

**Comment by tleyden** [comment]
This ticket is hard to act on.  Please re-file the ticket like this:

- Describe the problem you are seeing
- Exact steps / commands you took to run into the problem
- The expected vs actual behavior
