### ISSUE TITLE
Container usage from node.js app

### ISSUE THREAD

**Issue by acelvaros** [tleyden/open-ocr#97]
What are the setup and run instructions if I choose to run a node.js app get open-ocr (created in a docker container in BlueMix) as an engine to process uploaded files (on the server/linking a volume to a container)?

Can I run the container and access the image's filesystem via a bash shell for testing purposes?
If I simply try to run the container, it just won't start, it'll stay in "Shutdown" status.

Do I need to re-build the code or use a compiler? My test machine is with Windows.

Thank you

**Comment by tleyden** [comment]
node.js would talk to openocr via the rest api, and there are docs for that (but no code samples) 

I'm not sure what you mean by accessing the "images filesystem", what are you trying to do exactly?

Also, I would first just try to make it work in bluemix, verify via curl, and then document how you did it.  Then try to get your node.js app "in the mix", by writing code that hits the openocr rest api.

**Comment by tleyden** [comment]
Closing the issue since it doesn't look like there are any action items, but let's continue the discussion here since there isn't a better place for that (yet)

**Comment by tleyden** [comment]
I meant specific action items for changing openocr

**Comment by acelvaros** [comment]
Hi Traun,

Thanks for the quick reply. What I'm trying to achieve is send images
through that rest api call to the container and get the output in txt back.
Can it process pdf (with image) or image only format (like tiff)?

The reason I tried to access the container via a bash shell is to manually
run the conversion in the shell to test it if it is possible at all. Of
course I can emulate Linux and install but I wanted to save that step. I'm
pretty new with containers, and had the experience with MySQL that you can
run it in a bash shell and access the filesystem plus run MySQL for DDL and
DML, etc. And it is also possible to access the container through the
public id address provided by BlueMix.

Having thought about it, I suspect what the reason for my problem
(conatainer won't start) may be: I could not build the image properly under
the space I use for dev, I could only copy to the registry, and the
dockerfile might not have been used at all. What I did is I gave the cpi
command when in the Docker folder of open-ocr:

I could not run this:

bx ic build -t registry.mycompany.bluemix.net/myspace/open-ocr:v1 .
(the equivalent command using docker would be: docker build..., which
command would have used the current dir looking for the dockerfile. Maybe I
need to build the image elsewhere or download it from git and create an
image locally, then push it to my local repo?

I could only copy the image to my registry:
bx ic cpi tleyden5iwx/open-ocr registry.mycompany.bluemix.
net/myspace/open-ocr:v1

So I think I have the image but not built based on the Dockerfile.
I'm not sure I have the correct Dockerfile:

FROM ubuntu:14.04 ENV GOPATH /opt/go # Get dependencies RUN apt-get update
&& apt-get install -y \ git \ golang \ gcc \ libleptonica-dev \
libtesseract3 \ libtesseract-dev \ tesseract-ocr \ tesseract-ocr-eng \
tesseract-ocr-ara \ tesseract-ocr-bel \ tesseract-ocr-ben \
tesseract-ocr-bul \ tesseract-ocr-ces \ tesseract-ocr-dan \
tesseract-ocr-deu \ tesseract-ocr-ell \ tesseract-ocr-fin \
tesseract-ocr-fra \ tesseract-ocr-heb \ tesseract-ocr-hin \
tesseract-ocr-ind \ tesseract-ocr-isl \ tesseract-ocr-ita \
tesseract-ocr-jpn \ tesseract-ocr-kor \ tesseract-ocr-nld \
tesseract-ocr-nor \ tesseract-ocr-pol \ tesseract-ocr-por \
tesseract-ocr-ron \ tesseract-ocr-rus \ tesseract-ocr-spa \
tesseract-ocr-swe \ tesseract-ocr-tha \ tesseract-ocr-tur \
tesseract-ocr-ukr \ tesseract-ocr-vie \ tesseract-ocr-chi-sim \
tesseract-ocr-chi-tra # In theory, should be able to set export
TESSDATA_PREFIX=/usr/share/tesseract-ocr/, # but when I tried I still got
error: Error opening data file /usr/local/share/tessdata/eng.traineddata #
Workaround: just copy the data to where it expects RUN mkdir -p
/usr/local/share/tessdata/ && \ cp -R /usr/share/tesseract-ocr/tessdata/*
/usr/local/share/tessdata/ RUN mkdir -p $GOPATH # go get open-ocr RUN go
get -u -v -t github.com/tleyden/open-ocr # build open-ocr-httpd binary and
copy it to /usr/bin RUN cd $GOPATH/src/github.com/tleyden/open-ocr/cli-httpd
&& go build -v -o open-ocr-httpd && cp open-ocr-httpd /usr/bin # build
open-ocr-worker binary and copy it to /usr/bin RUN cd $GOPATH/src/
github.com/tleyden/open-ocr/cli-worker && go build -v -o open-ocr-worker &&
cp open-ocr-worker /usr/bin

How is it possible to send a command to the container to convert the image
to text? Using its ip and port in my javascript?
Do you have a working example for such a script? And commands with curl?

Definitely, I'll log the detailed set of commands if I do succeed,
specially that I don't use the public docker but IBM's dedicated BlueMix
Container Services which behaves a bit differently at least as far as the
commands need to be run.


Thank you

**Comment by tleyden** [comment]
It doesn't support pdf out of the box yet: see https://github.com/tleyden/open-ocr/issues/87

Ok so basically it sounds like:

- Due to a company policy, you aren't allowed to pull docker images from dockerhub?
- You're trying to rebuild the openocr docker images and publish to the bluemix docker image registry?

You might try taking bluemix and that constraint out of the picture temporarily, install docker on your local workstation, and follow the instructions in the [README](https://github.com/tleyden/open-ocr/blob/master/README.md) on how to install it and verify your installation via curl.  Then once you've got it all running and you can poke around, look into installing on bluemix.

**Comment by acelvaros** [comment]
So it means if everything is ideal I should be able to have a running
container? I'm not supposed to access the image if the container is
shutdown,am I? I'd be very surprised if it was the case.

I can not pull images to internal, dedicated bluemix, but can build an
image or copy them to the registry. My concern is why the dockerfile's
commands fail when I try to build the image. I'll try public bx and docker,
too. But I have a feeling I'll have the same image availble that way.
Asking some fellow colleagues on their experience.

Thx


2017. okt. 10. 17:04 ezt írta ("Traun Leyden" <notifications@github.com>):

It doesn't support pdf out of the box yet: see #87
<https://github.com/tleyden/open-ocr/issues/87>

Ok so basically it sounds like:

   - Due to a company policy, you aren't allowed to pull docker images from
   dockerhub?
   - You're trying to rebuild the openocr docker images and publish to the
   bluemix docker image registry?

You might try taking bluemix and that constraint out of the picture
temporarily, install docker on your local workstation, and follow the
instructions in the README
<https://github.com/tleyden/open-ocr/blob/master/README.md> on how to
install it and verify your installation via curl. Then once you've got it
all running and you can poke around, look into installing on bluemix.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tleyden/open-ocr/issues/97#issuecomment-335503037>, or mute
the thread

**Comment by tleyden** [comment]
> So it means if everything is ideal I should be able to have a running
container? 

After starting openocr, you should have several running containers.

> I'm not supposed to access the image if the container is
shutdown,am I? I'd be very surprised if it was the case.

When you say "image", what are you referring to?  I'm not sure if you are talking about docker images or actual images to be decoded.

> I can not pull images to internal, dedicated bluemix, but can build an
image or copy them to the registry. My concern is why the dockerfile's
commands fail when I try to build the image.

You probably don't even need to build the docker images, unless you have specific requirements.  Have you tried following these steps on your workstation yet?  https://github.com/tleyden/open-ocr#launching-openocr-command-runsh

**Comment by acelvaros** [comment]
Hi Traun,
I have some blockers getting Docker run. I have Win 7 and would need either
Win 10 or Win 7 with virtualization enabled in the BIOS, which I'm not
allowed to do now.
I'll try to update my OS and get back to you.

**Comment by acelvaros** [comment]
Hi Traun,

Seems like I managed to get the BIOS settings updated, enabling
virtualization, installed docker.

When running docker-compose up the logs I get you find in the attached
image . Does that mean the API is usable? How do I get the hostname/port?

**Comment by tleyden** [comment]
Oops, wrong button!  Great news, will take a look.  I don't see any logs, can you try using github web ui rather than email for that?

**Comment by acelvaros** [comment]
I attached a file in the previous note. Can you check? Or you mean try run
the commands so that it's visible on git? I'm not sure what you mean. I
just don't know I've been on the right path so far in docker and how to use
the api.
